# newrelic:
#   license_key: '3bebe19a32811a514cb3ad30ace05dba819db9c6'
#   verbose: 1
# agents:
#   incoming_mail:
#     # Full path to the the log file
#     log_path: log/incoming_mail.log
#     # Returns the number of matches for this term. Use Linux Regex formatting.
#     # Default: "[Ee]rror"
#     term: "[REJECT]"
#     # Provide any options to pass to grep when running.
#     # For example, to count non-matching lines, enter 'v'.
#     # Use the abbreviated format ('v' and not 'invert-match').
#     grep_options:
#   # my_logfile_2:
#     # Full path to the the log file
#     # log_path: log/onyx.log
#     # Returns the number of matches for this term. Use Linux Regex formatting.
#     # Default: "[Ee]rror"
#     # term: "[Ee]rror   "
#     # Provide any options to pass to grep when running.
#     # For example, to count non-matching lines, enter 'v'.
#     # Use the abbreviated format ('v' and not 'invert-match').
#     # grep_options:
